// Inline the extracted CSS into the JS bundle and write the Admin2 custom field file.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';

const js = readFileSync('build/blocks.js', 'utf8');
const cssFile = ['build/blocks.css', 'build/style.css'].find(existsSync);
const css = cssFile ? readFileSync(cssFile, 'utf8') : '';

if (!js.includes('__MAW_CSS__')) {
  throw new Error('Bundle is missing the __MAW_CSS__ placeholder (see src/main.js).');
}
if (/^\s*import\s.+from\s+['"]\.{1,2}\//m.test(js)) {
  throw new Error('Bundle contains relative imports; Admin2 cannot load it.');
}

const banner = '/* MAW Builder — generated by `npm run build` from src/. Do not edit. */\n';
mkdirSync('admin-next/fields', { recursive: true });
writeFileSync('admin-next/fields/blocks.js', banner + js.replace('"__MAW_CSS__"', JSON.stringify(css)));
console.log(`admin-next/fields/blocks.js written (${Math.round((js.length + css.length) / 1024)} KB)`);
