extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.subtitle:
              type: text
              label: Subtitle
              ordering@: header.title
        blocks:
          type: tab
          title: Blocks
          ordering@: content
          fields:
            header.hide_title:
              type: toggle
              label: Hide page title
              default: 0
              highlight: 1
              options: { 1: PLUGIN_ADMIN.YES, 0: PLUGIN_ADMIN.NO }
              validate: { type: bool }
            header.width:
              type: select
              label: Content width
              default: narrow
              options: { narrow: Narrow, default: Default, wide: Wide }
          import@:
            type: partials/blocks-field
            context: 'theme://blueprints'
